package com.shop.models;
// Generated Jun 20, 2019, 3:42:52 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Bill generated by hbm2java
 */
@Entity
@Table(name = "Bill", schema = "dbo", catalog = "ShopBadminton_Online")
public class Bill implements java.io.Serializable {

	private Integer id;
	private Account account;
	private Date date;
	private String fullname;
	private String phonenumber;
	private String address;
	private int totalPrice;
	private String status;
	private Set<BillDetail> billDetails = new HashSet<BillDetail>(0);

	public Bill() {
	}

	public Bill(Account account, Date date, String fullname, String phonenumber, String address,
			int totalPrice, String status) {
		this.account = account;
		this.date = date;
		this.fullname = fullname;
		this.phonenumber = phonenumber;
		this.address = address;
		this.totalPrice = totalPrice;
		this.status = status;
	}

	public Bill(Account account, Date date, String fullname, String phonenumber, String address,
			int totalPrice, String status, Set<BillDetail> billDetails) {
		this.account = account;
		this.date = date;
		this.fullname = fullname;
		this.phonenumber = phonenumber;
		this.address = address;
		this.totalPrice = totalPrice;
		this.status = status;
		this.billDetails = billDetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AccountID", nullable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Date", nullable = false, length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "Fullname", nullable = false)
	public String getFullname() {
		return this.fullname;
	}

	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	@Column(name = "Phonenumber", nullable = false)
	public String getPhonenumber() {
		return this.phonenumber;
	}

	public void setPhonenumber(String phonenumber) {
		this.phonenumber = phonenumber;
	}

	@Column(name = "Address", nullable = false)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "TotalPrice", nullable = false)
	public int getTotalPrice() {
		return this.totalPrice;
	}

	public void setTotalPrice(int totalPrice) {
		this.totalPrice = totalPrice;
	}

	@Column(name = "Status", nullable = false)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bill")
	public Set<BillDetail> getBillDetails() {
		return this.billDetails;
	}

	public void setBillDetails(Set<BillDetail> billDetails) {
		this.billDetails = billDetails;
	}

}
