package com.shop.models;
// Generated Jun 20, 2019, 3:42:52 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ExportProduct generated by hbm2java
 */
@Entity
@Table(name = "ExportProduct", schema = "dbo", catalog = "ShopBadminton_Online")
public class ExportProduct implements java.io.Serializable {

	private Integer id;
	private BillDetail billDetail;
	private ImportProduct importProduct;
	private int count;
	private int priceImport;
	private int priceExport;

	public ExportProduct() {
	}

	public ExportProduct(BillDetail billDetail, ImportProduct importProduct, int count, int priceImport,
			int priceExport) {
		this.billDetail = billDetail;
		this.importProduct = importProduct;
		this.count = count;
		this.priceImport = priceImport;
		this.priceExport = priceExport;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BillDetailID", nullable = false)
	public BillDetail getBillDetail() {
		return this.billDetail;
	}

	public void setBillDetail(BillDetail billDetail) {
		this.billDetail = billDetail;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ImportProductID", nullable = false)
	public ImportProduct getImportProduct() {
		return this.importProduct;
	}

	public void setImportProduct(ImportProduct importProduct) {
		this.importProduct = importProduct;
	}

	@Column(name = "Count", nullable = false)
	public int getCount() {
		return this.count;
	}

	public void setCount(int count) {
		this.count = count;
	}

	@Column(name = "PriceImport", nullable = false)
	public int getPriceImport() {
		return this.priceImport;
	}

	public void setPriceImport(int priceImport) {
		this.priceImport = priceImport;
	}

	@Column(name = "PriceExport", nullable = false)
	public int getPriceExport() {
		return this.priceExport;
	}

	public void setPriceExport(int priceExport) {
		this.priceExport = priceExport;
	}

}
