package com.shop.models;
// Generated Jun 20, 2019, 3:42:52 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ImportProduct generated by hbm2java
 */
@Entity
@Table(name = "ImportProduct", schema = "dbo", catalog = "ShopBadminton_Online")
public class ImportProduct implements java.io.Serializable {

	private Integer id;
	private Product product;
	private int quantity;
	private int price;
	private Date importDate;
	private int soldNumber;
	private Set<ExportProduct> exportProducts = new HashSet<ExportProduct>(0);

	public ImportProduct() {
	}

	public ImportProduct(Product product, int quantity, int price, Date importDate, int soldNumber) {
		this.product = product;
		this.quantity = quantity;
		this.price = price;
		this.importDate = importDate;
		this.soldNumber = soldNumber;
	}

	public ImportProduct(Product product, int quantity, int price, Date importDate, int soldNumber,
			Set<ExportProduct> exportProducts) {
		this.product = product;
		this.quantity = quantity;
		this.price = price;
		this.importDate = importDate;
		this.soldNumber = soldNumber;
		this.exportProducts = exportProducts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ProductID", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "Quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "Price", nullable = false)
	public int getPrice() {
		return this.price;
	}

	public void setPrice(int price) {
		this.price = price;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ImportDate", nullable = false, length = 10)
	public Date getImportDate() {
		return this.importDate;
	}

	public void setImportDate(Date importDate) {
		this.importDate = importDate;
	}

	@Column(name = "SoldNumber", nullable = false)
	public int getSoldNumber() {
		return this.soldNumber;
	}

	public void setSoldNumber(int soldNumber) {
		this.soldNumber = soldNumber;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "importProduct")
	public Set<ExportProduct> getExportProducts() {
		return this.exportProducts;
	}

	public void setExportProducts(Set<ExportProduct> exportProducts) {
		this.exportProducts = exportProducts;
	}

}
