package com.shop.models;
// Generated Jun 20, 2019, 3:42:52 PM by Hibernate Tools 4.3.5.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Price generated by hbm2java
 */
@Entity
@Table(name="Price"
    ,schema="dbo"
    ,catalog="ShopBadminton_Online"
)
public class Price  implements java.io.Serializable {


     private Integer id;
     private Product product;
     private Integer price;
     private Date beginDate;
     private Date endDate;

    public Price() {
    }

    public Price(Integer price, Date beginDate, Date endDate) {
        this.price = price;
        this.beginDate = beginDate;
        this.endDate = endDate;
    }
    public Price(Product product, Date beginDate, Date endDate) {
        this.product = product;
        this.beginDate = beginDate;
        this.endDate = endDate;
    }
    public Price(Product product, Integer price, Date beginDate, Date endDate) {
       this.product = product;
       this.price = price;
       this.beginDate = beginDate;
       this.endDate = endDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ProductID", nullable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

    
    @Column(name="Price")
    public Integer getPrice() {
        return this.price;
    }
    
    public void setPrice(Integer price) {
        this.price = price;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="BeginDate", nullable=false, length=10)
    public Date getBeginDate() {
        return this.beginDate;
    }
    
    public void setBeginDate(Date beginDate) {
        this.beginDate = beginDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="EndDate", nullable=true, length=10)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }




}


