package com.shop.models;
// Generated Jun 20, 2019, 3:42:52 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Statistic generated by hbm2java
 */
@Entity
@Table(name = "Statistic", schema = "dbo", catalog = "ShopBadminton_Online")
public class Statistic implements java.io.Serializable {

	private Integer id;
	private Product product;
	private Date statisticDate;
	private int revenue;
	private int benefit;
	private int amount;

	public Statistic() {
	}

	public Statistic(Product product, Date statisticDate, int revenue, int benefit) {
		this.product = product;
		this.statisticDate = statisticDate;
		this.revenue = revenue;
		this.benefit = benefit;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ProductID", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "StatisticDate", nullable = false, length = 10)
	public Date getStatisticDate() {
		return this.statisticDate;
	}

	public void setStatisticDate(Date statisticDate) {
		this.statisticDate = statisticDate;
	}

	@Column(name = "Revenue", nullable = false)
	public int getRevenue() {
		return this.revenue;
	}

	public void setRevenue(int revenue) {
		this.revenue = revenue;
	}

	@Column(name = "Benefit", nullable = false)
	public int getBenefit() {
		return this.benefit;
	}

	public void setBenefit(int benefit) {
		this.benefit = benefit;
	}

	@Column(name = "amount", nullable = true)
	public int getAmount() {
		return amount;
	}

	public void setAmount(int amount) {
		this.amount = amount;
	}
	


}
